name: "Deploy Library"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy application')"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
      # - name: Generate Git Tag
      #   run: |
      #     NEW_TAG="v$(node -e "console.log(require('./package.json').version)")"
      #     echo "Generated new tag: $NEW_TAG"
      #     echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
      #   if: success()
      # - name: create git tag
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "github-actions@users.noreply.github.com"
      #     git tag $NEW_TAG
      #     git push origin $NEW_TAG
